### ISSUE TITLE
Push helm charts for provider and admission controller to OCI repository

### ISSUE THREAD

**Issue by MartinWeindel** [ironcore-dev/gardener-extension-provider-ironcore#725]
# Summary

Automate creating Helm charts and pushing them to an OCI repository to allow using Helm references in the operator extension resource.
You may use a similar approach as the `gardener-extension-acl`.
See PR https://github.com/stackitcloud/gardener-extension-acl/pull/114.

## Basic example

The resulting operator extension resource can then be make use of them:
```yaml
apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: provider-ironcore
spec:
  resources:
    - kind: BackupBucket
      type: ironcore
    - kind: BackupEntry
      type: ironcore
    - kind: Bastion
      type: ironcore
    - kind: ControlPlane
      type: ironcore
    - kind: Infrastructure
      type: ironcore
    - kind: Worker
      type: ironcore
  deployment:
    admission:
      values:
        image:
          repository: .../admission-ironcore
          tag: v0.1.0
      runtimeCluster:
        helm:
          ociRepository:
            ref: my-oci-repository.example.com/some-path/admission-ironcore-runtime:v0.1.0
      virtualCluster:
        helm:
          ociRepository:
            ref: my-oci-repository.example.com/some-path/admission-ironcore-application:v0.1.0
    extension:
      runtimeClusterValues:
        image:
          repository: .../provider-ironcore
          tag: v0.1.0
      values:
        image:
          repository: .../provider-ironcore
          tag: v0.1.0
      helm:
        ociRepository:
          ref: my-oci-repository.example.com/some-path/gardener-extension-provider-ironcore:v0.1.0
```

## Motivation

Follow the standard pattern for Gardener extensions.
